config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root 'parks#index'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :park_reports
  resources :parks, only: [:edit, :update, :show, :index] do
    collection do
      get 'autocomplete'
      get 'tokyo_ward_info'
    end
  end
  resources :park_images, only: [:new, :create]
  resources :report_images, only: [:new, :create, :destroy, :index]
  resource :profile, only: %i[show edit update]
  resources :bookmarks, only: %i[index create destroy]
  
  root 'tops#index'
  get '/search', to: 'parks#index', as: 'search'
  get '/mypage', to: 'users#index'
  get '/terms_of_service', to: 'tops#terms_of_service'
  get '/privacy_policy', to: 'tops#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :sns_credentials, dependent: :destroy
  has_many :park_reports, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_parks, through: :bookmarks, source: :park
  
  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    sns_credential = SnsCredential.find_by(provider: auth.provider, uid: auth.uid)
    if sns_credential
      return sns_credential.user
    else
      user = User.find_or_create_by(email: auth.info.email) do |u|
        u.name = auth.info.name
        u.password = Devise.friendly_token[0, 20]
      end
      user.sns_credentials.create(provider: auth.provider, uid: auth.uid)
      return user
    end
  end

  def own?(object)
    id == object&.user_id
  end

  def bookmark(park)
    bookmark_parks << park
  end

  def unbookmark(park)
    bookmark_parks.destroy(park)
  end

  def bookmark?(park)
    bookmark_parks.include?(park)
  end

  def visited_tokyo_wards
    park_reports.select(:tokyo_ward_id).distinct.pluck(:tokyo_ward_id)
  end

  def visited_tokyo_wards_count
    visited_tokyo_wards.count
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]

  def show
    render partial: 'profiles/show'
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = t('flash_message.update.success', item: User.human_attribute_name(:profile))
      redirect_to mypage_path
    else
      flash.now['alert'] = t('flash_message.update.failure', item: User.human_attribute_name(:profile))
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/views/profiles/_show.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex-grow container mx-auto px-6 py-5">
  <div class="flex justify-center items-center">
    <p class="text-xl md:text-2xl text-park font-bold py-5 text-center">- <%= current_user.name %>さんのプロフィール -</p>
  </div>
  <%= turbo_frame_tag current_user do %>
  <div class="flex justify-center items-center py-10">
    <div class="card w-96 bg-base-100 shadow-xl">
      <div class="card-body">
        <div class="flex justify-center items-center avatar border-b-2 border-slate-200 pb-3">
          <div class="w-24 rounded-full ring ring-park ring-offset-base-100 ring-offset-2">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar.url %>
            <% else %>
              <%= image_tag 'avatar.jpg' %>
            <% end %>
          </div>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-2 pb-3">
          <p class="font-bold"><%= User.human_attribute_name(:name) %></p>
          <p class="text-park"><%= current_user.name %></p>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-2 pb-3">
          <p class="font-bold"><%= User.human_attribute_name(:email) %></p>
          <p class="text-park text-center break-all w-2/3"><%= current_user.email %></p>
        </div>
        <div class="pt-5 w-full">
          <%= link_to t('helpers.submit.edit'), edit_profile_path, class: "btn btn-secondary me-2 w-full" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<%= turbo_frame_tag current_user do %>
  <div class="flex justify-center items-center py-10">
    <div class="card w-96 bg-base-100 shadow-xl">
      <div class="card-body">
      <%= form_with model: @user, url: profile_path(@user), local: true do |f| %>
        <div class="border-b-2 border-slate-200 pb-6">
          <p class="pb-4">
            <%= f.label :プロフィール画像, class: "font-bold" %>
          </p>
          <%= f.file_field :avatar, class: "file-input file-input-bordered file-input-secondary w-full max-w-xs", style: "max-height: 40px;" %>
          <p class="text-sm pt-2">選択可能なファイル形式はjpg,jpeg,pngのみです<p>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-4 pb-1">
          <p class="font-bold"><%= User.human_attribute_name(:name) %></p>
          <p class="text-park pl-4">
            <%= f.text_field :name, autofocus: true, autocomplete: "name", class: "pl-3 mt-1 block placeholder-gray-400 rounded-lg border-2 border-gray-200" %>
          </p>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-4 pb-1">
        <% is_google_account = @user.sns_credential_ids.present? %>
          <p class="font-bold"><%= User.human_attribute_name(:email) %></p>
          <% if is_google_account %>
            <p class="pl-3 mt-1 block placeholder-gray-400 rounded-lg border-2 border-gray-200"><%= current_user.email%></p>
          <% else %>
            <p class="text-park">
              <%= f.text_field :email, autofocus: true, autocomplete: "email", class: "pl-3 mt-1 block placeholder-gray-400 rounded-lg border-2 border-gray-200" %>
            </p>
          <% end %>
        </div>
          <% if is_google_account %>
            <p class="text-sm pt-2">Googleアカウントの為メールの編集はできません<p>
          <% end %>
        <div class="pt-7 w-full">
          <%= f.submit '更新', class: "btn btn-secondary me-2 w-full" %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex-grow container mx-auto px-6 py-5">
  <div class="flex justify-center items-center">
    <div class="text-2xl md:text-3xl lg:text-4xl text-park text-center font-bold pb-5 px-8 border-b-2 border-park">
      <%= current_user.name %>さんのプロフィール
    </div>
  </div>
  <%= turbo_frame_tag current_user do %>
  <div class="flex justify-center items-center py-10">
    <div class="card w-96 bg-base-100 shadow-xl">
      <div class="card-body">
        <div class="flex justify-center items-center avatar border-b-2 border-slate-200 pb-3">
          <div class="w-24 rounded-full ring ring-park ring-offset-base-100 ring-offset-2">
            <% if current_user.avatar.present? %>
              <%= image_tag current_user.avatar.url %>
            <% else %>
              <%= image_tag 'avatar.jpg' %>
            <% end %>
          </div>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-2 pb-3">
          <p class="font-bold"><%= User.human_attribute_name(:name) %></p>
          <p class="text-park"><%= current_user.name %></P>
        </div>
        <div class="flex justify-center border-b-2 border-slate-200 pt-2 pb-3">
          <p class="font-bold"><%= User.human_attribute_name(:email) %></p>
          <p class="text-park"><%= current_user.email %></p>
        </div>
        <div class="pt-5 w-full">
          <%= link_to t('helpers.submit.edit'), edit_profile_path, class: "btn btn-secondary me-2 w-full" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>