config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root 'parks#index'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :park_reports
  resources :parks, only: [:edit, :update, :show, :index] do
    collection do
      get 'autocomplete'
      get 'tokyo_ward_info'
    end
  end
  resources :park_images, only: [:new, :create]
  resources :report_images, only: [:new, :create, :destroy, :index]
  resource :profile, only: %i[show edit update]
  resources :bookmarks, only: %i[index create destroy]
  
  root 'tops#index'
  get '/search', to: 'parks#index', as: 'search'
  get '/mypage', to: 'users#index'
  get '/terms_of_service', to: 'tops#terms_of_service'
  get '/privacy_policy', to: 'tops#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
    random_park = Park.pluck(:id).sample
    @park = Park.find(random_park)
    @park_images = @park.park_images
    @park_tokyo_ward = @park.tokyo_wards.first
  end

  def terms_of_service
  end

  def privacy_policy
  end
end

app/views/tops/_random_park.html.erb
<div class="flex justify-center items-center">
  <div class="card w-96 bg-accent shadow-xl">
    <figure class="px-10 pt-10">
      <div style="max-height: 200px; width: 100%; object-fit: cover;">
        <% if @park_images.present? && @park_images.first.url.present? %>
          <%= image_tag @park_images.first.url.url %>
        <% else %>
          <%= image_tag 'park.webp' %>
        <% end %> 
      </div>
    </figure>
    <div class="card-body items-center text-center">
      <div class="card-actions">
        <%= link_to 'この公園を詳しく見る', "#{park_path(@park)}", class: "bg-accent btn btn-primary", data: { turbo: false } %>
      </div>
    </div>
  </div>
</div>
<div class="text-center pt-5">
  <%= link_to '他の公園を条件で検索する', search_path, class: "text-park hover:bg-slate-200 rounded-lg px-4 py-2", data: { turbo: false } %>
</div>

app/views/tops/index.html.erb
<% content_for(:title, t('.title')) %>
<%= stylesheet_link_tag 'top' %>
<div class="main-container">
  <h1 class="text-center font-bold text-2xl md:text-4xl pt-10" style="padding-left: 0.5em;">休日は、ピクニックにいこう。</h1>
  <p class="text-center lg:text-lg pt-5">東京23区で新たな発見を</p>
  <div class="flex justify-center items-center flex-col md:flex-row pt-10">
    <%= turbo_frame_tag "park_info_frame" do %>
    <button class="btn custom-btn" onclick="random_park_modal.showModal()">行ったことある？？？</button>
    <dialog id="random_park_modal" class="modal">
      <div class="modal-box">
        <div>
          <form method="get" class="modal-backdrop text-park font-bold flex justify-end pr-5" action="<%= root_path %>", data: { turbo_frame: "park_info_frame" }>
            <button type="submit">×</button>
          </form>
          <div class="justify-center text-center pb-2 px-6">
            <% if @park.catchphrase.present? %>
              <p class="text-park font-bold text-lg md:text-2xl py-2 pb-3 border-b-2 border-park"><%= "#{@park.catchphrase}" %></p>
            <% else %>
              <p class="text-park py-2"><%= Park.human_attribute_name(:catchphrase) %>募集中<p>
            <% end %>
            <p class="text-park pt-3">- <%= @park_tokyo_ward.name %> -</p>
            <div class="text-park font-bold md:text-xl">
              <%= @park.name %>
            </div>
          </div>
          <%= render 'random_park' %>
        </div>
      </div>
      <form method="get" class="modal-backdrop" action="<%= root_path %>", data: { turbo_frame: "park_info_frame" }>
        <button type="submit">close</button>
      </form>
    </dialog>
    <% end %>
      <p class="text-center pt-2 pb-2 px-3">OR</p>
      <%= link_to '知ってる公園教えて！', new_park_report_path, class: "btn custom-btn" %>
  </div>
</div>
<div class="sub_container text-park px-5 py-10">
  <div>
    <p class="text-xl text-center font-bold pt-10">- 東京Picnicで出来ること -</p>
    <p class="text-center pt-3 text-xs sm:text-base">東京23区とは耳にするけれど、何がどこにあるんだろう。<br>
    行ったことがない場所もたくさんあるでしょう。<br>
    公園をきっかけにいろんな土地に行ってみませんか？<br>
    東京の新たな魅力を発見・共有しよう！</p>
  </div>
  <div class="flex justify-center items-center flex-col md:flex-row md:gap-x-10 px-3 mt-5 mb-5 pt-5 pb-5">
    <div class="card w-96 bg-accent shadow-xl">
      <div class="card-body">
        <h2 class="card-title">公園をランダムにおすすめ</h2>
        <p><br>
        東京には、たくさんの公園があります。<br>
        中でも、ピクニックにお勧めな公園を厳選。<br>
        聞いたことがない、魅力的な公園に出会えるかも。<br>
        </p>
        <div class="card-actions justify-end">
          <button class="btn btn-primary" onclick="random_park_modal.showModal()">見てみる</button>
        </div>
      </div>
    </div>
    <div class="pt-5">
      <%= image_tag 'random.jpg', class: "rounded-lg", size: "350x350" %>
    </div>
  </div>
  <div class="flex justify-center items-center flex-col md:flex-row md:gap-x-10 px-3 mt-5 mb-5 pt-5 pb-5">
    <div class="card w-96 bg-accent shadow-xl order-1 md:order-2">
      <div class="card-body">
        <h2 class="card-title">あなたに合った公園を見つけよう</h2>
        <p><br>
        目的別や23区を選択など<br>
        公園の情報を絞り込んで検索できます。<br>
        </p>
        <div class="card-actions justify-end">
          <%= link_to '見てみる', search_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="pt-5 order-2 md:order-1">
      <%= image_tag 'search.png', class: "rounded-lg shadow-xl", size: "350x350" %>
    </div>
  </div>
  <div class="flex justify-center items-center flex-col md:flex-row md:gap-x-10 px-3 mt-5 mb-5 pt-5 pb-5">
    <div class="card w-96 bg-accent shadow-xl">
      <div class="card-body">
        <h2 class="card-title">行った公園の日記を投稿しよう</h2>
        <p class="text-sm">※ログイン限定機能</p>
        <p><br>
        あなたしか知らない公園や、<br>
        お気に入りの公園などをみんなに共有しよう！<br>
        公園に行った日のことを日記のように保管。<br>
        </p>
        <div class="card-actions justify-end">
          <%= link_to '見てみる', new_park_report_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
    <div class="pt-5">
      <%= image_tag 'post.jpg', class: "rounded-lg shadow-xl", size: "350x350" %>
    </div>
  </div>
</div>

app/views/tops/privacy_policy.html.erb
<div class="container mx-auto px-4 py-8 bg-accent">
  <h1 class="text-center text-3xl font-bold text-gray-800 mb-4"><%= t('navbar.privacy_policy') %></h1>
  <p class="mb-4">
    東京Picnic（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「当社サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
  </p>
  <div class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <h2 class="text-xl font-semibold mb-2">お客様から取得する情報</h2>
    <p class="mb-4">
      当社は、お客様から以下の情報を取得します。<br>
      ・氏名(ニックネームやペンネームも含む)<br>
      ・メールアドレス<br>
      ・写真<br>
      ・外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報<br>
      ・お客様の位置情報
    </p>

    <h2 class="text-xl font-semibold mb-2">お客様の情報を利用する目的</h2>
    <p class="mb-4">
      当社は、お客様から取得した情報を、以下の目的のために利用します。<br>
      ・当社サービスに関する登録の受付、お客様の本人確認、認証のため<br>
      ・お客様の当社サービスの利用履歴を管理するため<br>
      ・当社サービスにおけるお客様の行動履歴を分析し、当社サービスの維持改善に役立てるため<br>
      ・当社のサービスに関するご案内をするため<br>
      ・お客様からのお問い合わせに対応するため<br>
      ・当社の規約や法令に違反する行為に対応するため<br>
      ・以上の他、当社サービスの提供、維持、保護及び改善のため<br>
    </p>

    <h2 class="text-xl font-semibold mb-2">安全管理のために講じた措置</h2>
    <p class="mb-4">
      当社がお客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。
    </p>

    <h2 class="text-xl font-semibold mb-2">第三者提供</h2>
    <p class="mb-4">
      当社は、お客様から取得する情報のうち、個人データ(個人情報保護法第16条第3項)に該当するものについては、あらかじめお客様の同意を得ずに、第三者(日本国外にある者を含みます。)に提供しません。<br>
      但し、次の場合は除きます。
      ・個人データの取り扱いを外部に委託する場合<br>
      ・当社や当社サービスが買収された場合<br>
      ・事業パートナーと共同利用する場合(具体的な共同利用がある場合は、その内容を別途公表します。)<br>
      ・その他、法律によって合法的に第三者提供が許されている場合
    </p>

    <h2 class="text-xl font-semibold mb-2">アクセス解析ツール</h2>
    <p class="mb-4">
      当社は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。
      Googleアナリティクスは、トラフィックデータ収集のためにCookieを使用しています。
      トラフィックデータは匿名で収集されており、個人を特定するものではありません。
      Cookieを無効にすれば、これらの情報収集を拒否することができます。詳しくはお使いのブラウザの設定をご確認ください。
      Googleアナリティクスについて、詳しくは以下からご確認ください。<br>
      <br>
      <%= link_to 'Googleアナリティクスについてはこちら', 'https://marketingplatform.google.com/about/analytics/terms/jp/' %>
    </p>

    <h2 class="text-xl font-semibold mb-2">プライバシーポリシーの変更</h2>
    <p class="mb-4">
      当社は、必要に応じて、本ポリシーの内容を変更します。
      この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知いたします。
    </p>

    <h2 class="text-xl font-semibold mb-2">お問い合わせ窓口</h2>
    <p class="mb-4">
      お客様の情報開示、情報の訂正、利用停止、削除をご希望の場合は，下記の窓口までお願いいたします。
      <br>
      <br>
      <%= link_to 'お問い合わせ窓口はこちら', 'https://docs.google.com/forms/d/e/1FAIpQLSdyw7joRau7Jm644B9mvHDtvyXBuUFk1ayLR98jnns_bbjr6A/viewform?usp=sf_link', class: "link link-hover" %>
    </p>

    <p class="text-right">以上</p>

    <p class="text-center">制定日：2024年6月1日</p>

  </div>
</div>

app/views/tops/terms_of_service.html.erb
<div class="flex-grow container mx-auto px-6 py-5">  
  <h1 class="text-center text-3xl font-bold text-gray-800 mb-5">利用規約</h1>
    <p class="mb-5">
      この利用規約（以下，「本規約」といいます。）は，東京Picnic（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。<br>
      登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
    </p>

  <div class="bg-accent shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第1条（適用）</h2>
        <p class="mb-4 pl-3">
          1. 本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。<br>
          2. 当社は本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。<br>
          3. 本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第2条（利用登録）</h2>
        <p class="mb-4 pl-3">
          1. 本サービスにおいては，登録希望者が本規約に同意の上，当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。<br>
          2. 当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。<br>
          <div class="bg-accent shadow-md rounded px-8 py-3 mb-4">
            1. 利用登録の申請に際して虚偽の事項を届け出た場合<br>
            2. 本規約に違反したことがある者からの申請である場合<br>
            3. その他，当社が利用登録を相当でないと判断した場合<br>
          </div>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第3条（ユーザーIDおよびパスワードの管理）</h2>
        <p class="mb-4 pl-3">
          1. ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。<br>
          2. ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。<br>
          3. ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当社に故意又は重大な過失がある場合を除き，当社は一切の責任を負わないものとします。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第4条（利用料金および支払方法）</h2>
        <p class="mb-4 pl-3">
          1. ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。<br>
          2. ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年14．6％の割合による遅延損害金を支払うものとします。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第5条（禁止事項）</h2>
      <p class="mb-4 pl-3">
        ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。<br>
        1. 法令または公序良俗に違反する行為<br>
        2. 犯罪行為に関連する行為<br>
        3. 本サービスの内容等，本サービスに含まれる著作権，商標権ほか知的財産権を侵害する行為<br>
        4. 当社，ほかのユーザー，またはその他第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為<br>
        5. 本サービスによって得られた情報を商業的に利用する行為<br>
        6. 当社のサービスの運営を妨害するおそれのある行為<br>
        7. 不正アクセスをし，またはこれを試みる行為<br>
        8. 他のユーザーに関する個人情報等を収集または蓄積する行為<br>
        9. 不正な目的を持って本サービスを利用する行為<br>
        10. 本サービスの他のユーザーまたはその他の第三者に不利益，損害，不快感を与える行為<br>
        11. 他のユーザーに成りすます行為<br>
        12. 当社が許諾しない本サービス上での宣伝，広告，勧誘，または営業行為<br>
        13. 面識のない異性との出会いを目的とした行為<br>
        14. 当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為<br>
        15. その他，当社が不適切と判断する行為<br>
      </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第6条（本サービスの提供の停止等）</h2>
        <p class="pl-3">
          1. 当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。<br>
          <div class="bg-accent shadow-md rounded px-8 py-3 mb-4">
            1. 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br>
            2. 地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合<br>
            3. コンピュータまたは通信回線等が事故により停止した場合<br>
            4. その他，当社が本サービスの提供が困難と判断した場合<br>
          </div>
        </p>
        <p class="mb-4 pl-3">
          2. 当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第7条（利用制限および登録抹消）</h2>
        <p class="mb-4 pl-3">
        1. 当社は，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，ユーザーに対して，本サービスの全部もしくは一部の利用を制限し，またはユーザーとしての登録を抹消することができるものとします。<br>
          <div class="bg-accent shadow-md rounded px-8 py-3 mb-4">
            1. 本規約のいずれかの条項に違反した場合<br>
            2. 登録事項に虚偽の事実があることが判明した場合<br>
            3. 料金等の支払債務の不履行があった場合<br>
            4. 当社からの連絡に対し，一定期間返答がない場合<br>
            5. 本サービスについて，最終の利用から一定期間利用がない場合<br>
            6. その他，当社が本サービスの利用を適当でないと判断した場合<br>
            7. 当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。<br>
          </div>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第8条（退会）</h2>
        <p class="mb-4 pl-3">
        ユーザーは，当社の定める退会手続により，本サービスから退会できるものとします。
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第9条（保証の否認および免責事項）</h2>
        <p class="mb-4 pl-3">
        1. 当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br>
        2. 当社は，本サービスに起因してユーザーに生じたあらゆる損害について、当社の故意又は重過失による場合を除き、一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。<br>
        3. 前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。<br>
        4. 当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第10条（サービス内容の変更等）</h2>
        <p class="mb-4 pl-3">
        当社は，ユーザーへの事前の告知をもって、本サービスの内容を変更、追加または廃止することがあり、ユーザーはこれを承諾するものとします。
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第11条（利用規約の変更）</h2>
        <p class="pl-3">
          1. 当社は以下の場合には、ユーザーの個別の同意を要せず、本規約を変更することができるものとします。<br>
            <div class="bg-accent shadow-md rounded px-8 py-3 mb-4">
              1. 本規約の変更がユーザーの一般の利益に適合するとき。<br>
              2. 本規約の変更が本サービス利用契約の目的に反せず、かつ、変更の必要性、変更後の内容の相当性その他の変更に係る事情に照らして合理的なものであるとき。<br>
            </div>
        </p>
        <p class="mb-4 pl-3">
          2. 当社はユーザーに対し、前項による本規約の変更にあたり、事前に、本規約を変更する旨及び変更後の本規約の内容並びにその効力発生時期を通知します。<br>
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第12条（個人情報の取扱い）</h2>
        <p class="mb-4 pl-3">
        当社は，本サービスの利用によって取得する個人情報については，当社「プライバシーポリシー」に従い適切に取り扱うものとします。
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第13条（通知または連絡）</h2>
        <p class="mb-4 pl-3">
        ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。当社は,ユーザーから,当社が別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第14条（権利義務の譲渡の禁止）</h2>
        <p class="mb-4 pl-3">
        ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。
        </p>
    </div>

    <div class="pb-3">
      <h2 class="text-xl font-semibold pb-3">第15条（準拠法・裁判管轄）</h2>
        <p class="mb-4 pl-3">
        1. 本規約の解釈にあたっては，日本法を準拠法とします。<br>
        2. 本サービスに関して紛争が生じた場合には，当社の本店所在地を管轄する裁判所を専属的合意管轄とします。<br>
        </p>
    </div>
    <p style="text-align: right;">以上</p>
    <p class="text-center">制定日：2024年6月1日</p>
  </div>
</div>