config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root 'parks#index'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :park_reports
  resources :parks, only: [:edit, :update, :show, :index] do
    collection do
      get 'autocomplete'
      get 'tokyo_ward_info'
    end
  end
  resources :park_images, only: [:new, :create]
  resources :report_images, only: [:new, :create, :destroy, :index]
  resource :profile, only: %i[show edit update]
  resources :bookmarks, only: %i[index create destroy]
  
  root 'tops#index'
  get '/search', to: 'parks#index', as: 'search'
  get '/mypage', to: 'users#index'
  get '/terms_of_service', to: 'tops#terms_of_service'
  get '/privacy_policy', to: 'tops#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_before_login_header.html.erb
<header class="w-full navbar">
  <div class="flex justify-between items-center w-full">
    <div class="flex-1 px-2">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', class: "logo rounded-lg hover:bg-slate-200", size: "100x100" %>
      <% end %>
    </div>
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost rounded-btn text-lg text-slate-600 hover:bg-slate-200">Menu</div>
        <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-base-100 rounded-box w-52 mt-4">
          <li>
            <%= link_to t('navbar.post'), new_park_report_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <li>
            <%= link_to t('navbar.search'), search_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <li>
            <%= link_to t('navbar.new_user'), new_user_registration_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <li>
            <%= link_to t('navbar.login'), new_user_session_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li> 
        </ul>
      </div>
    </div>
  </div>  
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div role="alert" class="alert bg-emerald-600 text-black border-none font-semibold shadow-lg mt-5">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<div class="px-3">
  <% flash.each do |message_type, message| %>
    <div id="flash-message" class="rounded-b text-park font-bold px-4 py-5" role="alert">
      <%= message %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="flex w-full footer p-3 bg-lime-800 text-neutral-content">
  <nav class="p-3">
    <h6 class="footer-title text-slate-100">Services</h6> 
    <%= link_to t('navbar.random'), root_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.search'), search_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.post'), new_park_report_path, class: "link link-hover text-slate-100" %>
  </nav> 
  <nav class="p-3">
    <h6 class="footer-title text-slate-100">Personal</h6> 
    <%= link_to t('navbar.new_user'), new_user_registration_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.mypage'), mypage_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.login'), new_user_session_path, class: "link link-hover text-slate-100" %>
  </nav> 
  <nav class="p-3">
    <h6 class="footer-title text-slate-100">Legal</h6> 
    <%= link_to t('navbar.terms_of_service'), terms_of_service_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.privacy_policy'), privacy_policy_path, class: "link link-hover text-slate-100" %>
    <%= link_to t('navbar.contact'), 'https://docs.google.com/forms/d/e/1FAIpQLSdyw7joRau7Jm644B9mvHDtvyXBuUFk1ayLR98jnns_bbjr6A/viewform?usp=sf_link', class: "link link-hover text-slate-100" %>
  </nav>
</footer>

app/views/shared/_header.html.erb
<header class="w-full navbar">
  <div class="flex justify-between items-center w-full">
    <div class="flex-1 px-2">
      <%= link_to root_path do %>
        <%= image_tag 'logo.png', class: "logo rounded-lg hover:bg-slate-200", size: "100x100" %>
      <% end %>
    </div>
    <div class="dropdown dropdown-end">
      <div tabindex="0" role="button" class="btn btn-ghost text-lg rounded-btn text-slate-600 hover:bg-slate-200">Menu</div>
        <ul tabindex="0" class="menu dropdown-content z-[1] p-2 shadow bg-base-100 rounded-box w-52 mt-4">
          <li>
            <%= link_to t('navbar.post'), new_park_report_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <li>
            <%= link_to t('navbar.search'), search_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <br>
          <li>
            <%= link_to t('navbar.mypage'), mypage_path, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li>
          <li>
            <%= link_to t('navbar.logout'), destroy_user_session_path, data: { turbo_method: :delete}, class: "text-park font-semibold hover:bg-slate-200 rounded-lg px-4 py-2" %>
          </li> 
        </ul>
      </div>
    </div>
  </div>  
</header>

app/views/shared/_loading.html.erb
<dialog id="loading-modal" class="modal" data-loading-target="modal">
  <div class="modal-box flex justify-center items-center">
    <img src="<%= asset_path('loading_sandwitch.gif') %>" alt="Proccesing GIF">
  </div>
  <form method="dialog" class="modal-backdrop">
    <button>close</button>
  </form>
</dialog>

app/views/shared/_map.html.erb
<iframe
  frameborder="0" style="width: 100%; height: 100%; border:0"
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['GOOGLE_API_KEY'] %>&q=place_id:<%= @park.googlemaps_place_id %>"
  allowfullscreen>
</iframe>