config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [:registrations, :password], controllers: {
    sessions: 'admins/sessions'
  }
  namespace :admins do
    root 'parks#index'
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  resources :park_reports
  resources :parks, only: [:edit, :update, :show, :index] do
    collection do
      get 'autocomplete'
      get 'tokyo_ward_info'
    end
  end
  resources :park_images, only: [:new, :create]
  resources :report_images, only: [:new, :create, :destroy, :index]
  resource :profile, only: %i[show edit update]
  resources :bookmarks, only: %i[index create destroy]
  
  root 'tops#index'
  get '/search', to: 'parks#index', as: 'search'
  get '/mypage', to: 'users#index'
  get '/terms_of_service', to: 'tops#terms_of_service'
  get '/privacy_policy', to: 'tops#privacy_policy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/park_report.rb
class ParkReport < ApplicationRecord
  belongs_to :user
  belongs_to :park
  belongs_to :tokyo_ward
  has_many :report_images, dependent: :destroy
  accepts_nested_attributes_for :report_images
  attr_accessor :park_name

  validates :title, presence: true
end

app/controllers/park_reports_controller.rb
class ParkReportsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :find_current_user_report, only: %i[edit update]
  before_action :find_report, only: %i[show destroy]
  
  def index
    @park_reports = current_user.park_reports.includes(:park, :report_images).order(created_at: :desc)
    @visited_wards_count = current_user.visited_tokyo_wards_count
    @visited_wards = current_user.visited_tokyo_wards
    @tokyo_wards = TokyoWard.all
    render partial: 'park_reports/index'
  end

  def show
    @report_image = ReportImage.new
  end

  def new
    @park_report = ParkReport.new
    @park_report.report_images.build
    @park_report.park_name = params[:park_name]
    @park_report.tokyo_ward_id = params[:tokyo_ward_id]
  end

  def edit; end

  def create
    @park_report = ParkReport.new(recieve_params)
    @park_name = params[:park_report][:park_name]
    @park = Park.find_by(name: @park_name)

    if @park
      @tokyo_ward = @park.tokyo_wards.first
    else
      receive_tokyo_ward
    end

    if @park.nil?
      flash.now[:danger] = "指定された公園が見つかりませんでした。東京23区にある公園を入力してください。"
      @park_report.park_name = @park_name
      @park_report.tokyo_ward_id = params[:park_report][:tokyo_ward_id]
    else
      save_park_report
    end
  end

  def update
    if @park_report.update(edit_params)
      flash[:success] = t('flash_message.update.success', item: ParkReport.human_attribute_name(:report))
      redirect_to @park_report
    else
      flash[:danger] = t('flash_message.update.failure', item: ParkReport.human_attribute_name(:report))
      render :show, status: :unprocessable_entity
    end
  end

  def destroy
    @park = @park_report.park
    if @park_report.destroy
      
      flash[:success] = t('flash_message.destroy.success', item: ParkReport.human_attribute_name(:report))
      redirect_to mypage_path
    else
      flash.now[:danger] = t('flash_message.destroy.failure', item: ParkReport.human_attribute_name(:report))
      render :show, status: :unprocessable_entity
    end
  end

  private

  def find_current_user_report
    @park_report = current_user.park_reports.find(params[:id])
  end

  def find_report
    @park_report = ParkReport.includes(:report_images, :park).find(params[:id])
  end

  def recieve_params
    params.require(:park_report).permit(:park_name, :tokyo_ward_id, :date, :title, :comment, report_images_attributes: [:url])
  end

  def report_params
    params.require(:park_report).permit(:date, :title, :comment, report_images_attributes: [:url]).merge(park_id: @park.id, tokyo_ward_id: @tokyo_ward.id)
  end

  def edit_params
    params.require(:park_report).permit(:date, :title, :comment)
  end

  def receive_tokyo_ward
    if params[:park_report][:tokyo_ward_id].present?
      @tokyo_ward = TokyoWard.find(params[:park_report][:tokyo_ward_id])
      create_park_and_associate_tokyo_ward
    else
      flash.now[:danger] = "区を選択してください"
      render :new, status: :unprocessable_entity
    end
  end

  def save_park_report
    @park_report = current_user.park_reports.build(report_params)
    if @park_report.save
      flash[:success] = t('flash_message.post.success')
      redirect_to park_path(@park)
    else
      flash[:danger] = t('flash_message.post.failure')
      render :new, status: :unprocessable_entity
    end
  end

  def create_park_and_associate_tokyo_ward
    latitude = @tokyo_ward.latitude
    longitude = @tokyo_ward.longitude
    location = "#{latitude},#{longitude}"

    google_places_service = GooglePlacesService.new
    response = google_places_service.search(location, @park_name)

    park_info = response['results'].first
      if park_info.nil?
        flash[:danger] = "公園が東京23区にないか、区が間違っています。"
        render :new, status: :unprocessable_entity
        return
      end
    place_id = park_info['place_id']
    park_lat = park_info['geometry']['location']['lat']
    park_lng = park_info['geometry']['location']['lng']
    web_response = google_places_service.get_website(place_id)
    website = web_response['result']['website']
  
    @park = Park.create(name: @park_name, googlemaps_place_id: place_id, website_url: website, latitude: park_lat, longitude: park_lng)
    @park.tokyo_wards << @tokyo_ward

    add_image_to_park(google_places_service, park_info, @park)
  end

  def add_image_to_park(google_places_service, park_info, park)
    return unless park_info['photos'].present?

    photo_reference = park_info['photos'].first['photo_reference']
    image_url = google_places_service.get_photo_url(photo_reference)

    image_download_service = ImageDownloadService.new(image_url)
    temp_file = image_download_service.download_and_process

    if temp_file
      park_image = park.park_images.create(url: File.open(temp_file.path))
    end
  end
end

app/views/park_reports/_edit.html.erb
<%= form_with(model: @park_report, url: park_report_path, remote: true, local: true, class: "justify-between item-center") do |f| %>
  <div class="my-5 flex flex-col px-5">
    <%= f.label :date, ParkReport.human_attribute_name(:date) + "(任意)" %>
    <%= f.date_field :date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="mt-8 mb-8 flex flex-col px-5">
    <%= f.label :title, ParkReport.human_attribute_name(:title) %>
    <%= f.text_field :title, placeholder: 'どんな公園？', class: "textarea textarea-primary", data: { focus_target: "title" } %>
  </div>
  <div class="mt-8 mb-8 flex flex-col px-5">
    <%= f.label :comment, ParkReport.human_attribute_name(:comment) %>
    <%= f.text_area :comment, placeholder: '自由に記入して思い出を記録しよう', class: "textarea textarea-primary" %>
  </div>
  <div class="btn btn-ghost rounded-btn hover:bg-slate-200 text-park mt-5 w-full">
    <%= f.submit t('helpers.submit.create') %>
  </div>
<% end %>

app/views/park_reports/_index.html.erb
<div class="py-5">
  <p class="text-xl md:text-2xl text-park font-bold py-5 text-center">- <%= current_user.name %>さんの公園日記 -</p>
</div>
<div class="flex justify-center items-center pb-5">
  <p class="bg-accent btn btn-primary w-auto h-auto text-lg font-semibold" onclick="ward_collection.showModal()">\ click me /<br>行った23区の数 : <%= @visited_wards_count %> 個</p>
  <dialog id="ward_collection" class="modal">
    <div class="modal-box">
      <%= render 'ward_collection' %>
    </div>
    <form method="dialog" class="modal-backdrop">
      <button>close</button>
    </form>
  </dialog>
</div>
<div class="px-8 flex justify-center items-center md:justify-between flex-col md:flex-row gap-y-8 xl:gap-x-5 lg:gap-x-5 sm:gap-x-5 pb-8  grid xl:grid-cols-4 lg:grid-cols-3  sm:grid-cols-2">
  <% @park_reports.each do |park_report| %>
    <div class="card bg-base-100 shadow-xl flex flex-col md:gap-x-10" style="height: 380px;">
      <figure>
        <div>
          <% if park_report.report_images.present? && park_report.report_images.first.url.present? %>
            <%= image_tag park_report.report_images.first.url.url, class: "w-full h-auto object-cover"%>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
        </div>
      </figure>
      <div class="card-body bg-white rounded-lg">
          <p><%= park_report.date %></p>
        <%= link_to "#{park_report.park.name}", park_path(park_report.park), class: "card-title hover:bg-slate-200 rounded-lg px-4 py-1" %>
        <p class="border-b-2 border-slate-200"></p>
        <%= link_to "#{park_report.title}", park_report_path(park_report), class: "pl-5 text-park font-bold hover:bg-slate-200 rounded-lg px-4 py-1" %>
      </div>
    </div>
  <% end %>
</div>

<div class="px-8 flex justify-center items-center">
    <%= link_to '公園の思い出を投稿する', new_park_report_path, class: "bg-accent btn btn-primary me-2 w-auto font-semibold" %>
</div>

app/views/park_reports/_ward_collection.html.erb
<h2 class="text-center text-park text-base md:text-xl font-bold py-5">行ったことない区の公園を探しに行こう</h2>
<div class="grid grid-cols-3 gap-4 md:grid-cols-4">
  <% @tokyo_wards.each do |ward| %>
    <%= link_to search_path(q: { tokyo_wards_id_eq: ward.id }), class: "border p-4 text-center rounded-lg block hover:bg-slate-200" do %>
      <p class="font-bold text-xs md:text-base"><%= ward.name %></p>
      <% if @visited_wards.include?(ward.id) %>
        <%= image_tag 'gone.jpg', alt: "Visited", class: "mx-auto mt-2 rounded-lg" %>
      <% else %>
        <%= image_tag 'not_go.jpg', alt: "Not Visited", class: "mx-auto mt-2 rounded-lg" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/park_reports/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="flex-grow container mx-auto px-6 py-5" data-controller="loading">
  <%= render 'shared/loading' %>
  <div class="flex justify-center items-center">
    <div class="text-2xl md:text-3xl lg:text-4xl text-park text-center font-bold pb-5 px-8 border-b-2 border-park">
    新規投稿
    </div>
  </div>
  <div class="flex justify-center items-center">
    <div class="card bg-accent text-park shadow-xl mt-8 flex flex-col w-96">
      <figure class="flex">
        <%= form_with(model: @park_report, url: park_reports_path, local: true) do |f| %>
          <%= render 'shared/error_messages', object: @park_report %>
          <div data-controller="autocomplete" data-autocomplete-min-length-value="2" data-autocomplete-url-value="/parks/autocomplete" role="combobox">
            <div class="mt-8 flex flex-col px-5">
              <%= f.label :name, Park.human_attribute_name(:name) %>
              <%= f.text_field :park_name, data: { autocomplete_target: 'input' }, placeholder: '公園の名前を入れてね', class: "input input-bordered input-primary bg-accent shadow w-full max-w-xs" %>
              <%= f.hidden_field :name, data: { autocomplete_target: 'hidden' } %>
              <%= f.hidden_field :park_id, data: { autocomplete_target: 'parkId' } %>
              <ul class="list-group mt-4 text-xs" data-autocomplete-target="results"></ul>
            </div>
            <div class="mt-8 flex flex-col w-2/3 px-5">
              <%= f.collection_select :tokyo_ward_id, TokyoWard.all, :id, :name, { include_blank: "区を選択" }, { class: "select select-primary bg-accent max-w-xs shadow", data: { autocomplete_target: 'ward' } } %>
            </div>
          </div>
          <div class="my-5 flex flex-col px-5">
            <%= f.label :date, ParkReport.human_attribute_name(:date) %>
            <%= f.date_field :date, class: "block shadow rounded-md border bg-accent outline-none border-success px-3 py-2 mt-2 w-full" %>
          </div>
            <%= f.fields_for :report_images do |report_image| %>
              <div class="field mt-8 flex flex-col px-5">
                <%= report_image.label :url, "写真" %>
                <%= report_image.file_field :url, class: "file-input file-input-bordered file-input shadow bg-accent border-success w-full max-w-xs", style: "max-height: 40px;"%>
              </div>
            <% end %>
          <div class="mt-8 mb-8 flex flex-col px-5">
            <%= f.label :title, ParkReport.human_attribute_name(:title)+"(⚠︎必須)" %>
            <%= f.text_field :title, placeholder: 'どんな公園だった？', class: "textarea textarea-primary bg-accent shadow" %>
          </div>
          <div class="mt-8 mb-8 flex flex-col px-5">
            <%= f.label :comment, ParkReport.human_attribute_name(:comment) %>
            <%= f.text_area :comment, placeholder: '自由に記入して思い出を残そう', class: "textarea textarea-primary bg-accent shadow" %>
          </div>
          <div class="my-5 flex flex-col px-5">
            <button class="btn btn-primary" data-loading-target="submit">
              <%= f.submit t('helpers.submit.submit') %>
            </button>
          </div>
        <% end %>
      </figure>
    </div>
  </div>
</div>

app/views/park_reports/show.html.erb
<% content_for(:title, t('.title')) %>
<div  class="flex-grow container mx-auto px-6 py-10">
  <div class="flex justify-center items-center md:justify-between flex-col md:flex-row md:gap-x-10 px-3">
    <div class="card bg-base-100 shadow-xl flex flex-col md:flex-row w-full h-auto md:h-full object-cover">
      <figure class="rounded-md">
        <div>
          <% if @park_report.report_images.present? && @park_report.report_images.first.url.present? %>
            <%= image_tag @park_report.report_images.first.url.url %>
          <% else %>
            <%= image_tag 'default.png' %>
          <% end %>
        </div>
      </figure>
    </div>
    <div class="card-body bg-white rounded-md w-full h-auto md:h-full object-cover">
        <h2 class="text-xl pb-2 pl-3 border-b-2 border-slate-200 text-park">
          <%= link_to "#{@park_report.park.name}", "#{park_path(@park_report.park)}", class: "hover:bg-slate-200 rounded-lg px-4 py-2" %>
          <%= link_to Park.human_attribute_name(:website), "#{@park_report.park.website_url}", class: "badge badge border-b-2 border-park text-park hover:bg-slate-200" %>
        </h2>
        <div class="flex justify-between border-b-2 border-slate-200 pb-1 text-park">
          <p class="pl-8"><%= @park_report.date %></p>
          <div data-controller="focus">
            <% if user_signed_in? && current_user.own?(@park_report) %>
              <button class="pr-5" data-focus-target="edit" onclick="report_edit.showModal()"><i class="fa-solid fa-pen"></i><%= t('helpers.submit.edit') %></button>
            <% end %>
            <dialog id="report_edit" class="modal">
              <div class="modal-box">
                <%= render 'edit' %>
              </div>
              <form method="dialog" class="modal-backdrop">
                <button>close</button>
              </form>
            </dialog>
          </div>
          <% if user_signed_in? && current_user.own?(@park_report) %>
            <div class="pr-5">
              <%= link_to park_report_path(@park_report), data: { turbo_method: :delete, turbo_confirm: '投稿を削除しますか？画像も全て削除されます。'} do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </div>
          <% end %>
        </div>
        <div class="border-b-2 border-slate-200 pb-1 text-park">
          <p class="pl-8"><%= @park_report.title %><p>
        </div>
        <div class="border-b-2 border-slate-200 pb-1 text-park">
          <p class="pl-8"><%= @park_report.comment %><p>
        </div>
      </div>
    </div>

    <div class="flex justify-center items-center md:justify-between flex-col md:flex-row gap-y-8 py-10 px-8 gap-y-8 xl:gap-x-5 sm:gap-x-5 pb-8 grid xl:grid-cols-4 sm:grid-cols-3">
      <% @park_report.report_images.each do |report_image| %>
        <div>
          <div class="card bg-base-100 shadow-xl flex flex-col md:gap-x-10 rounded-lg" >
            <figure>
              <div style="width: 100%; object-fit: cover;">
              <% if report_image.url.present? %>
                <%= image_tag report_image.url.url, class: "w-full h-auto object-cover rounded-lg "%>
              <% end %>
              </div>
            </figure>
          </div>
          <% if user_signed_in? &&  current_user.own?(@park_report) %>
            <div class="pt-3">
              <%= link_to report_image_path(report_image), data: { turbo_method: :delete, turbo_confirm: '画像を削除しますか？'} do %>
                <i class="fa-regular fa-trash-can"></i>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="flex justify-center items-center">
      <% if user_signed_in? && current_user.own?(@park_report) %>
        <button class="btn hover:bg-slate-200 rounded-lg px-4 py-2" onclick="add_image.showModal()"><%= t('helpers.submit.add_image') %></button>
        <dialog id="add_image" class="modal">
          <div class="modal-box">
            <p class="text-park font-bold pb-5 text-center"><%= t('helpers.submit.choice_image') %></p>
            <%= render 'report_images/form', report_image: @report_image %>
          </div>
          <form method="dialog" class="modal-backdrop">
            <button>close</button>
          </form>
        </dialog>
      <% end %>
    </div>
    <div class="flex justify-center items-center pt-3">
      <%= link_to :back do %>
        <button class="btn hover:bg-slate-200 rounded-lg px-4 py-2">戻る</button>
      <% end %>
    </div>
  </div>
</div>